# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: pg
data:
  POSTGRES_DB: testDB
  POSTGRES_USER: testUSER
  POSTGRES_PASSWORD: testPASSWORD
  #PGDATA: /data/pgdata