apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: pg
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      #targetPort: 5432
  selector:
    app: pg

