version: "3.9"

networks:
  backend:
    name: textify
    internal: false
    attachable: false
    enable_ipv6: false
    driver: bridge
#Remaind it!
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.21.1.0/24

services:
  postgres:
    image: postgres:14.5-alpine3.16
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 150M

  api:
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 400M
    build:
      context: ./api
      dockerfile: api.dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
      
