version: "3.9"

networks:
  backend:
    name: textify
    internal: false
    attachable: false
    enable_ipv6: false
    driver: bridge
#Remaind it!
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.21.1.0/24

services:
  postgres:
    image: postgres:14.1-alpine3.15
    environment:
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "testUSER"
      POSTGRES_PASSWORD: "testPASSWORD"
    networks:
      - backend
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testUSER -d testDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M

  api:
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "testUSER"
      POSTGRES_PASSWORD: "testPASSWORD"
    build:
      context: ./api
      dockerfile: api.dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
      
