spring:
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL10Dialect"
    show-sql: true
    hibernate:
      ddl-auto: update