apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: dev-ns
  labels:
    app: pg
spec:
  selector:
    matchLabels:
      app: pg
  serviceName: postgres
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 2

  template:
    metadata:
      labels:
        app: pg
    spec:
      terminationGracePeriodSeconds: 20
      serviceAccountName: dev-read-sa
      containers:
        - name: pg #DNS_LABLE
          image: postgres:15.1-alpine3.17
          imagePullPolicy: IfNotPresent
          ports:
            - name: db
              containerPort: 5432
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 600Mi
          env:
            - name: POSTGRES_DB
              value: $DBNAME
            - name: POSTGRES_USER
              value: $DBUSERNAME
            - name: POSTGRES_PASSWORD
              value: $DBPASS
            - name: PGDATA
              value: "/data/pgdata"


          volumeMounts:
            - name: pg-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi