apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: dev-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo