apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: pg
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pg
  ports:
    - name: db
      port: 5432
      #targetPort: 5432


